export const INIT_STORIES = 'INIT_STORIES';
export const SET_STORIES = 'SET_STORIES';
export const SET_STORY = 'SET_STORY';
export const DELETE_STORY = 'DELETE_STORY';
export const SAVE_EDITED_STORY = 'SAVE_EDITED_STORY';
export const SAVE_NEW_STORY = 'SAVE_NEW_STORY';
export const SAVE_SUCCESS = 'SAVE_SUCCESS';

export const GET_TEAM = 'GET_TEAM';
export const SET_TEAM = 'SET_TEAM';
export const ADD_TEAM_MEMBER = 'ADD_TEAM_MEMBER';
export const REMOVE_TEAM_MEMBER = 'REMOVE_TEAM_MEMBER';

export const AUTHENTICATION_START = 'AUTHENTICATION_START';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';
export const AUTHENTICATION_LOGOUT = 'AUTHENTICATION_LOGOUT';
